"""AUTOGENERATED FILE! DO NOT EDIT!

Custom AST.
"""

import ast as _ast

from prescrypt.ast.mixin import Mixin

NodeVisitor = _ast.NodeVisitor
NodeTransformer = _ast.NodeTransformer
dump = _ast.dump
unparse = _ast.unparse


class AST(_ast.AST, Mixin):
    pass


class mod(_ast.mod, Mixin):
    pass


class stmt(_ast.stmt, Mixin):
    pass


class expr(_ast.expr, Mixin):
    pass


class expr_context(_ast.expr_context, Mixin):
    pass


class boolop(_ast.boolop, Mixin):
    pass


class operator(_ast.operator, Mixin):
    pass


class unaryop(_ast.unaryop, Mixin):
    pass


class cmpop(_ast.cmpop, Mixin):
    pass


class comprehension(_ast.comprehension, Mixin):
    pass


class excepthandler(_ast.excepthandler, Mixin):
    pass


class arguments(_ast.arguments, Mixin):
    pass


class arg(_ast.arg, Mixin):
    pass


class keyword(_ast.keyword, Mixin):
    pass


class alias(_ast.alias, Mixin):
    pass


class withitem(_ast.withitem, Mixin):
    pass


class match_case(_ast.match_case, Mixin):
    pass


class pattern(_ast.pattern, Mixin):
    pass


class type_ignore(_ast.type_ignore, Mixin):
    pass


class slice(_ast.slice, Mixin):
    pass


class Module(_ast.Module, mod, Mixin):
    pass


class Interactive(_ast.Interactive, mod, Mixin):
    pass


class Expression(_ast.Expression, mod, Mixin):
    pass


class FunctionType(_ast.FunctionType, mod, Mixin):
    pass


class FunctionDef(_ast.FunctionDef, stmt, Mixin):
    pass


class AsyncFunctionDef(_ast.AsyncFunctionDef, stmt, Mixin):
    pass


class ClassDef(_ast.ClassDef, stmt, Mixin):
    pass


class Return(_ast.Return, stmt, Mixin):
    pass


class Delete(_ast.Delete, stmt, Mixin):
    pass


class Assign(_ast.Assign, stmt, Mixin):
    pass


class AugAssign(_ast.AugAssign, stmt, Mixin):
    pass


class AnnAssign(_ast.AnnAssign, stmt, Mixin):
    pass


class For(_ast.For, stmt, Mixin):
    pass


class AsyncFor(_ast.AsyncFor, stmt, Mixin):
    pass


class While(_ast.While, stmt, Mixin):
    pass


class If(_ast.If, stmt, Mixin):
    pass


class With(_ast.With, stmt, Mixin):
    pass


class AsyncWith(_ast.AsyncWith, stmt, Mixin):
    pass


class Match(_ast.Match, stmt, Mixin):
    pass


class Raise(_ast.Raise, stmt, Mixin):
    pass


class Try(_ast.Try, stmt, Mixin):
    pass


class TryStar(_ast.TryStar, stmt, Mixin):
    pass


class Assert(_ast.Assert, stmt, Mixin):
    pass


class Import(_ast.Import, stmt, Mixin):
    pass


class ImportFrom(_ast.ImportFrom, stmt, Mixin):
    pass


class Global(_ast.Global, stmt, Mixin):
    pass


class Nonlocal(_ast.Nonlocal, stmt, Mixin):
    pass


class Expr(_ast.Expr, stmt, Mixin):
    pass


class Pass(_ast.Pass, stmt, Mixin):
    pass


class Break(_ast.Break, stmt, Mixin):
    pass


class Continue(_ast.Continue, stmt, Mixin):
    pass


class BoolOp(_ast.BoolOp, expr, Mixin):
    pass


class NamedExpr(_ast.NamedExpr, expr, Mixin):
    pass


class BinOp(_ast.BinOp, expr, Mixin):
    pass


class UnaryOp(_ast.UnaryOp, expr, Mixin):
    pass


class Lambda(_ast.Lambda, expr, Mixin):
    pass


class IfExp(_ast.IfExp, expr, Mixin):
    pass


class Dict(_ast.Dict, expr, Mixin):
    pass


class Set(_ast.Set, expr, Mixin):
    pass


class ListComp(_ast.ListComp, expr, Mixin):
    pass


class SetComp(_ast.SetComp, expr, Mixin):
    pass


class DictComp(_ast.DictComp, expr, Mixin):
    pass


class GeneratorExp(_ast.GeneratorExp, expr, Mixin):
    pass


class Await(_ast.Await, expr, Mixin):
    pass


class Yield(_ast.Yield, expr, Mixin):
    pass


class YieldFrom(_ast.YieldFrom, expr, Mixin):
    pass


class Compare(_ast.Compare, expr, Mixin):
    pass


class Call(_ast.Call, expr, Mixin):
    pass


class FormattedValue(_ast.FormattedValue, expr, Mixin):
    pass


class JoinedStr(_ast.JoinedStr, expr, Mixin):
    pass


class Constant(_ast.Constant, expr, Mixin):
    pass


class Attribute(_ast.Attribute, expr, Mixin):
    pass


class Subscript(_ast.Subscript, expr, Mixin):
    pass


class Starred(_ast.Starred, expr, Mixin):
    pass


class Name(_ast.Name, expr, Mixin):
    pass


class List(_ast.List, expr, Mixin):
    pass


class Tuple(_ast.Tuple, expr, Mixin):
    pass


class Slice(_ast.Slice, expr, Mixin):
    pass


class Load(_ast.Load, expr_context, Mixin):
    pass


class Store(_ast.Store, expr_context, Mixin):
    pass


class Del(_ast.Del, expr_context, Mixin):
    pass


class And(_ast.And, boolop, Mixin):
    pass


class Or(_ast.Or, boolop, Mixin):
    pass


class Add(_ast.Add, operator, Mixin):
    pass


class Sub(_ast.Sub, operator, Mixin):
    pass


class Mult(_ast.Mult, operator, Mixin):
    pass


class MatMult(_ast.MatMult, operator, Mixin):
    pass


class Div(_ast.Div, operator, Mixin):
    pass


class Mod(_ast.Mod, operator, Mixin):
    pass


class Pow(_ast.Pow, operator, Mixin):
    pass


class LShift(_ast.LShift, operator, Mixin):
    pass


class RShift(_ast.RShift, operator, Mixin):
    pass


class BitOr(_ast.BitOr, operator, Mixin):
    pass


class BitXor(_ast.BitXor, operator, Mixin):
    pass


class BitAnd(_ast.BitAnd, operator, Mixin):
    pass


class FloorDiv(_ast.FloorDiv, operator, Mixin):
    pass


class Invert(_ast.Invert, unaryop, Mixin):
    pass


class Not(_ast.Not, unaryop, Mixin):
    pass


class UAdd(_ast.UAdd, unaryop, Mixin):
    pass


class USub(_ast.USub, unaryop, Mixin):
    pass


class Eq(_ast.Eq, cmpop, Mixin):
    pass


class NotEq(_ast.NotEq, cmpop, Mixin):
    pass


class Lt(_ast.Lt, cmpop, Mixin):
    pass


class LtE(_ast.LtE, cmpop, Mixin):
    pass


class Gt(_ast.Gt, cmpop, Mixin):
    pass


class GtE(_ast.GtE, cmpop, Mixin):
    pass


class Is(_ast.Is, cmpop, Mixin):
    pass


class IsNot(_ast.IsNot, cmpop, Mixin):
    pass


class In(_ast.In, cmpop, Mixin):
    pass


class NotIn(_ast.NotIn, cmpop, Mixin):
    pass


class ExceptHandler(_ast.ExceptHandler, excepthandler, Mixin):
    pass


class MatchValue(_ast.MatchValue, pattern, Mixin):
    pass


class MatchSingleton(_ast.MatchSingleton, pattern, Mixin):
    pass


class MatchSequence(_ast.MatchSequence, pattern, Mixin):
    pass


class MatchMapping(_ast.MatchMapping, pattern, Mixin):
    pass


class MatchClass(_ast.MatchClass, pattern, Mixin):
    pass


class MatchStar(_ast.MatchStar, pattern, Mixin):
    pass


class MatchAs(_ast.MatchAs, pattern, Mixin):
    pass


class MatchOr(_ast.MatchOr, pattern, Mixin):
    pass


class TypeIgnore(_ast.TypeIgnore, type_ignore, Mixin):
    pass


class Index(_ast.Index, slice, Mixin):
    pass


class ExtSlice(_ast.ExtSlice, slice, Mixin):
    pass


class Suite(_ast.Suite, mod, Mixin):
    pass


class AugLoad(_ast.AugLoad, expr_context, Mixin):
    pass


class AugStore(_ast.AugStore, expr_context, Mixin):
    pass


class Param(_ast.Param, expr_context, Mixin):
    pass


class Num(_ast.Num, Constant, expr, Mixin):
    pass


class Str(_ast.Str, Constant, expr, Mixin):
    pass


class Bytes(_ast.Bytes, Constant, expr, Mixin):
    pass


class NameConstant(_ast.NameConstant, Constant, expr, Mixin):
    pass


class Ellipsis(_ast.Ellipsis, Constant, expr, Mixin):
    pass


from .converter import parse
