"""AUTOGENERATED FILE! DO NOT EDIT!

Custom AST.
"""
from __future__ import annotations

import ast as _ast
from typing import Any

from prescrypt.ast.mixin import Mixin

NodeVisitor = _ast.NodeVisitor
NodeTransformer = _ast.NodeTransformer
dump = _ast.dump
unparse = _ast.unparse

ellipsis = type(...)


class AST(_ast.AST, Mixin):
    pass


class mod(_ast.mod, Mixin):
    pass


class stmt(_ast.stmt, Mixin):
    pass


class expr(_ast.expr, Mixin):
    pass


class expr_context(_ast.expr_context, Mixin):
    pass


class boolop(_ast.boolop, Mixin):
    pass


class operator(_ast.operator, Mixin):
    pass


class unaryop(_ast.unaryop, Mixin):
    pass


class cmpop(_ast.cmpop, Mixin):
    pass


class comprehension(_ast.comprehension, Mixin):
    target: expr
    iter: expr
    ifs: list[expr]
    is_async: int


class excepthandler(_ast.excepthandler, Mixin):
    pass


class arguments(_ast.arguments, Mixin):
    posonlyargs: list[arg]
    args: list[arg]
    vararg: None | arg
    kwonlyargs: list[arg]
    kw_defaults: list[None] | list[expr]
    kwarg: None | arg
    defaults: list[expr]


class arg(_ast.arg, Mixin):
    arg: str
    annotation: None | expr
    type_comment: None


class keyword(_ast.keyword, Mixin):
    arg: None | str
    value: expr


class alias(_ast.alias, Mixin):
    name: str
    asname: None | str


class withitem(_ast.withitem, Mixin):
    context_expr: expr
    optional_vars: None | expr


class match_case(_ast.match_case, Mixin):
    pattern: pattern
    guard: None
    body: list[stmt]


class pattern(_ast.pattern, Mixin):
    pass


class type_ignore(_ast.type_ignore, Mixin):
    pass


class slice(_ast.slice, Mixin):
    pass


class Module(_ast.Module, mod, Mixin):
    body: list[stmt]
    type_ignores: Any


class Interactive(_ast.Interactive, mod, Mixin):
    body: Any


class Expression(_ast.Expression, mod, Mixin):
    body: Any


class FunctionType(_ast.FunctionType, mod, Mixin):
    argtypes: Any
    returns: Any


class FunctionDef(_ast.FunctionDef, stmt, Mixin):
    name: str
    args: arguments
    body: list[stmt]
    decorator_list: list[expr]
    returns: None | expr
    type_comment: None


class AsyncFunctionDef(_ast.AsyncFunctionDef, stmt, Mixin):
    name: str
    args: arguments
    body: list[stmt]
    decorator_list: list[expr]
    returns: None | expr
    type_comment: None


class ClassDef(_ast.ClassDef, stmt, Mixin):
    name: str
    bases: list[expr]
    keywords: list[keyword]
    body: list[stmt]
    decorator_list: list[expr]


class Return(_ast.Return, stmt, Mixin):
    value: None | expr


class Delete(_ast.Delete, stmt, Mixin):
    targets: list[expr]


class Assign(_ast.Assign, stmt, Mixin):
    targets: list[expr]
    value: expr
    type_comment: None


class AugAssign(_ast.AugAssign, stmt, Mixin):
    target: expr
    op: operator
    value: expr


class AnnAssign(_ast.AnnAssign, stmt, Mixin):
    target: expr
    annotation: expr
    value: None | expr
    simple: int


class For(_ast.For, stmt, Mixin):
    target: expr
    iter: expr
    body: list[stmt]
    orelse: list[stmt]
    type_comment: None


class AsyncFor(_ast.AsyncFor, stmt, Mixin):
    target: expr
    iter: expr
    body: list[stmt]
    orelse: list[stmt]
    type_comment: None


class While(_ast.While, stmt, Mixin):
    test: expr
    body: list[stmt]
    orelse: list[stmt]


class If(_ast.If, stmt, Mixin):
    test: expr
    body: list[stmt]
    orelse: list[stmt]


class With(_ast.With, stmt, Mixin):
    items: list[withitem]
    body: list[stmt]
    type_comment: None


class AsyncWith(_ast.AsyncWith, stmt, Mixin):
    items: list[withitem]
    body: list[stmt]
    type_comment: None


class Match(_ast.Match, stmt, Mixin):
    subject: expr
    cases: list[match_case]


class Raise(_ast.Raise, stmt, Mixin):
    exc: None | expr
    cause: None | expr


class Try(_ast.Try, stmt, Mixin):
    body: list[stmt]
    handlers: list[excepthandler]
    orelse: list[stmt]
    finalbody: list[stmt]


class TryStar(_ast.TryStar, stmt, Mixin):
    body: Any
    handlers: Any
    orelse: Any
    finalbody: Any


class Assert(_ast.Assert, stmt, Mixin):
    test: expr
    msg: None | expr


class Import(_ast.Import, stmt, Mixin):
    names: list[alias]


class ImportFrom(_ast.ImportFrom, stmt, Mixin):
    module: None | str
    names: list[alias]
    level: int


class Global(_ast.Global, stmt, Mixin):
    names: list[str]


class Nonlocal(_ast.Nonlocal, stmt, Mixin):
    names: list[str]


class Expr(_ast.Expr, stmt, Mixin):
    value: expr


class Pass(_ast.Pass, stmt, Mixin):
    pass


class Break(_ast.Break, stmt, Mixin):
    pass


class Continue(_ast.Continue, stmt, Mixin):
    pass


class BoolOp(_ast.BoolOp, expr, Mixin):
    op: boolop
    values: list[expr]


class NamedExpr(_ast.NamedExpr, expr, Mixin):
    target: expr
    value: expr


class BinOp(_ast.BinOp, expr, Mixin):
    left: expr
    op: operator
    right: expr


class UnaryOp(_ast.UnaryOp, expr, Mixin):
    op: unaryop
    operand: expr


class Lambda(_ast.Lambda, expr, Mixin):
    args: arguments
    body: expr


class IfExp(_ast.IfExp, expr, Mixin):
    test: expr
    body: expr
    orelse: expr


class Dict(_ast.Dict, expr, Mixin):
    keys: list[None] | list[expr]
    values: list[expr]


class Set(_ast.Set, expr, Mixin):
    elts: list[expr]


class ListComp(_ast.ListComp, expr, Mixin):
    elt: expr
    generators: list[comprehension]


class SetComp(_ast.SetComp, expr, Mixin):
    elt: expr
    generators: list[comprehension]


class DictComp(_ast.DictComp, expr, Mixin):
    key: expr
    value: expr
    generators: list[comprehension]


class GeneratorExp(_ast.GeneratorExp, expr, Mixin):
    elt: expr
    generators: list[comprehension]


class Await(_ast.Await, expr, Mixin):
    value: expr


class Yield(_ast.Yield, expr, Mixin):
    value: None | expr


class YieldFrom(_ast.YieldFrom, expr, Mixin):
    value: expr


class Compare(_ast.Compare, expr, Mixin):
    left: expr
    ops: list[cmpop]
    comparators: list[expr]


class Call(_ast.Call, expr, Mixin):
    func: expr
    args: list[expr]
    keywords: list[keyword]


class FormattedValue(_ast.FormattedValue, expr, Mixin):
    value: expr
    conversion: int
    format_spec: None | expr


class JoinedStr(_ast.JoinedStr, expr, Mixin):
    values: list[expr]


class Constant(_ast.Constant, expr, Mixin):
    value: None | bytes | complex | ellipsis | float | int | str
    kind: None | str


class Attribute(_ast.Attribute, expr, Mixin):
    value: expr
    attr: str
    ctx: expr_context


class Subscript(_ast.Subscript, expr, Mixin):
    value: expr
    slice: expr
    ctx: expr_context


class Starred(_ast.Starred, expr, Mixin):
    value: expr
    ctx: expr_context


class Name(_ast.Name, expr, Mixin):
    id: str
    ctx: expr_context


class List(_ast.List, expr, Mixin):
    elts: list[expr]
    ctx: expr_context


class Tuple(_ast.Tuple, expr, Mixin):
    elts: list[expr]
    ctx: expr_context


class Slice(_ast.Slice, expr, Mixin):
    lower: None | expr
    upper: None | expr
    step: None | expr


class Load(_ast.Load, expr_context, Mixin):
    pass


class Store(_ast.Store, expr_context, Mixin):
    pass


class Del(_ast.Del, expr_context, Mixin):
    pass


class And(_ast.And, boolop, Mixin):
    pass


class Or(_ast.Or, boolop, Mixin):
    pass


class Add(_ast.Add, operator, Mixin):
    pass


class Sub(_ast.Sub, operator, Mixin):
    pass


class Mult(_ast.Mult, operator, Mixin):
    pass


class MatMult(_ast.MatMult, operator, Mixin):
    pass


class Div(_ast.Div, operator, Mixin):
    pass


class Mod(_ast.Mod, operator, Mixin):
    pass


class Pow(_ast.Pow, operator, Mixin):
    pass


class LShift(_ast.LShift, operator, Mixin):
    pass


class RShift(_ast.RShift, operator, Mixin):
    pass


class BitOr(_ast.BitOr, operator, Mixin):
    pass


class BitXor(_ast.BitXor, operator, Mixin):
    pass


class BitAnd(_ast.BitAnd, operator, Mixin):
    pass


class FloorDiv(_ast.FloorDiv, operator, Mixin):
    pass


class Invert(_ast.Invert, unaryop, Mixin):
    pass


class Not(_ast.Not, unaryop, Mixin):
    pass


class UAdd(_ast.UAdd, unaryop, Mixin):
    pass


class USub(_ast.USub, unaryop, Mixin):
    pass


class Eq(_ast.Eq, cmpop, Mixin):
    pass


class NotEq(_ast.NotEq, cmpop, Mixin):
    pass


class Lt(_ast.Lt, cmpop, Mixin):
    pass


class LtE(_ast.LtE, cmpop, Mixin):
    pass


class Gt(_ast.Gt, cmpop, Mixin):
    pass


class GtE(_ast.GtE, cmpop, Mixin):
    pass


class Is(_ast.Is, cmpop, Mixin):
    pass


class IsNot(_ast.IsNot, cmpop, Mixin):
    pass


class In(_ast.In, cmpop, Mixin):
    pass


class NotIn(_ast.NotIn, cmpop, Mixin):
    pass


class ExceptHandler(_ast.ExceptHandler, excepthandler, Mixin):
    type: None | expr
    name: None | str
    body: list[stmt]


class MatchValue(_ast.MatchValue, pattern, Mixin):
    value: expr


class MatchSingleton(_ast.MatchSingleton, pattern, Mixin):
    value: None | int


class MatchSequence(_ast.MatchSequence, pattern, Mixin):
    patterns: list[pattern]


class MatchMapping(_ast.MatchMapping, pattern, Mixin):
    keys: list[expr]
    patterns: list[pattern]
    rest: str


class MatchClass(_ast.MatchClass, pattern, Mixin):
    cls: expr
    patterns: list[pattern]
    kwd_attrs: list[str]
    kwd_patterns: list[pattern]


class MatchStar(_ast.MatchStar, pattern, Mixin):
    name: None | str


class MatchAs(_ast.MatchAs, pattern, Mixin):
    pattern: None
    name: None | str


class MatchOr(_ast.MatchOr, pattern, Mixin):
    patterns: list[pattern]


class TypeIgnore(_ast.TypeIgnore, type_ignore, Mixin):
    lineno: Any
    tag: Any


class Index(_ast.Index, slice, Mixin):
    pass


class ExtSlice(_ast.ExtSlice, slice, Mixin):
    pass


class Suite(_ast.Suite, mod, Mixin):
    pass


class AugLoad(_ast.AugLoad, expr_context, Mixin):
    pass


class AugStore(_ast.AugStore, expr_context, Mixin):
    pass


class Param(_ast.Param, expr_context, Mixin):
    pass


class Num(_ast.Num, Constant, expr, Mixin):
    n: Any


class Str(_ast.Str, Constant, expr, Mixin):
    s: Any


class Bytes(_ast.Bytes, Constant, expr, Mixin):
    s: Any


class NameConstant(_ast.NameConstant, Constant, expr, Mixin):
    value: Any
    kind: Any


class Ellipsis(_ast.Ellipsis, Constant, expr, Mixin):
    pass


class Function(FunctionDef):
    _fields = ("name", "args", "body")


from .converter import parse  # noqa
