image: alpine/latest
packages:
  - uv
  - nox
  - gcc
  - python3-dev
  - nodejs

secrets:
  - b88a4c2c-944c-42a6-9fbb-7483049c458a

sources:
  - git@git.sr.ht:~sfermigier/prescrypt

tasks:
  - install: |
      cd prescrypt
      uv sync
  - test: |
      cd prescrypt
      uv run pytest -q --tb=short
  - lint: |
      cd prescrypt
      uv run ruff check
  - nox: |
      cd prescrypt
      nox

triggers:
  - action: email
    condition: failure
    to: sf@fermigier.com
