image: alpine/latest
packages:
  - uv
  - gcc
  - python3-dev

secrets:
  - b88a4c2c-944c-42a6-9fbb-7483049c458a

sources:
  - git@git.sr.ht:~sfermigier/prescrypt-ng

tasks:
  - install: |
      cd prescrypt-ng
      uv sync
  - test: |
      cd prescrypt-ng
      uv run pytest -q --tb=short
  - lint: |
      cd prescrypt-ng
      uv run ruff check
      uv run ty check src
  - nox: |
      cd prescrypt-ng
      uvx nox

triggers:
  - action: email
    condition: failure
    to: sf@fermigier.com
