import ast
import inspect

# language=Python
PREAMBLE = '''\
"""AUTOGENERATED FILE! DO NOT EDIT!

Custom AST.
"""

import ast as _ast
from prescrypt.ast.mixin import Mixin


NodeVisitor = _ast.NodeVisitor
NodeTransformer = _ast.NodeTransformer
dump = _ast.dump
unparse = _ast.unparse

'''

POSTAMBLE = """\
from .converter import parse
"""


def main():
    print(PREAMBLE)

    classes = []

    for obj in vars(ast).values():
        if not isinstance(obj, type):
            continue
        if not issubclass(obj, ast.AST):
            continue

        classes.append(obj)

    classes.sort(key=lambda x: len(inspect.getmro(x)))

    for cls in classes:
        name = cls.__name__

        # debug(cls, inspect.getmro(cls), name)

        parents = []
        for cls2 in inspect.getmro(cls)[1:-1]:
            if cls2.__name__[0].isupper():
                continue
            parents.append(cls2.__name__)

        parents += ["Mixin"]
        parents_str = ", ".join(parents)

        print(f"class {name}(_ast.{name}, {parents_str}):")
        print("    pass\n\n")

    print(POSTAMBLE, end="")


if __name__ == "__main__":
    main()
