import ast
import inspect

# language=Python
PREAMBLE = '''\
"""AUTOGENERATED FILE! DO NOT EDIT!

Custom AST.
"""

import ast as _ast
from prescrypt.ast.mixin import Mixin


NodeVisitor = _ast.NodeVisitor
NodeTransformer = _ast.NodeTransformer
dump = _ast.dump
unparse = _ast.unparse

'''

POSTAMBLE = """\
class Function(FunctionDef):
    _fields = ("name", "args", "body")


from .converter import parse
"""


def main():
    print(PREAMBLE)

    classes = []

    for obj in vars(ast).values():
        if not isinstance(obj, type):
            continue
        if not issubclass(obj, ast.AST):
            continue

        classes.append(obj)

    classes.sort(key=lambda x: len(inspect.getmro(x)))

    for cls in classes:
        cls_name = cls.__name__
        parents = get_parents(cls)
        parents_str = ", ".join(parents)

        print(f"class {cls_name}(_ast.{cls_name}, {parents_str}):")
        print("    pass\n\n")

    print(POSTAMBLE, end="")


def get_parents(cls):
    for parent in inspect.getmro(cls)[1:-1]:
        parent_name = parent.__name__

        if parent_name == "Constant":
            yield "Constant"

        if parent_name[0].islower():
            yield parent_name

    yield "Mixin"


if __name__ == "__main__":
    main()
